

 
//路由懒加载反感
// const brands  = resolve => require(['../components/content/brand.vue'], resolve)
// const categories  = resolve => require(['../components/content/category.vue'], resolve)
// const center = resolve => require(['../components/sideNav/center.vue'], resolve)
// const workplat = resolve => require(['../components/sideNav/workplat.vue'], resolve)
// const bookingNav= resolve => require(['../components/sideNav/booking.vue'], resolve)
// const login= resolve => require(['../components/login/login.vue'], resolve)
// const repolist= resolve => require(['../components/content/repos.vue'], resolve)
// const creatRepo= resolve => require(['../components/content/createrepo.vue'], resolve)
// const createuser= resolve => require(['../components/content/createuser.vue'], resolve)
// const allusers= resolve => require(['../components/content/users.vue'], resolve)
// const createbrand= resolve => require(['../components/content/createbrand.vue'], resolve)
// const createprd= resolve => require(['../components/content/createProduct.vue'], resolve)
// const products= resolve => require(['../components/content/products.vue'], resolve)
// const product= resolve => require(['../components/sideNav/product.vue'], resolve)
// const skus= resolve => require(['../components/content/sku.vue'], resolve)
// const bookingForm= resolve => require(['../components/booking/booking-form.vue'], resolve)
// const creatcats= resolve => require(['../components/content/createcatory.vue'], resolve)
// const bookingList= resolve => require(['../components/booking/booking-list.vue'], resolve)
// const creatCategory= resolve => require(['../components/content/createcatory.vue'], resolve)
// const deliveryNav= resolve => require(['../components/sideNav/delivery.vue'], resolve)
// const deliveryBookingList= resolve => require(['../components/delivery/booking-list.vue'], resolve)
// const intoRepo= resolve => require(['../components/content/createIntoRepo.vue'], resolve)
// const updateProduct  = resolve => require(['../components/content/updateProduct.vue'], resolve)
// const inRepos  = resolve => require(['../components/content/intoRepos.vue'], resolve)
// const shipDetail  = resolve => require(['../components/delivery/shipDetail.vue'], resolve)
// const workStep  = resolve => require(['../components/statistics/workstep.vue'], resolve)
// const userAction  = resolve => require(['../components/authority/userAction.vue'], resolve)
// const actionList  = resolve => require(['../components/authority/actionList.vue'], resolve)
// const updateAction  = resolve => require(['../components/authority/updateAction.vue'], resolve)
// const dToAuth  = resolve => require(['../components/login/dToAuth.vue'], resolve)
